openapi: 3.0.1
info:
  title: serverless openapi test
  description: 'this is serverless openapi test'
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'

paths:
  /hello:
    get:
      summary: hello world
      operationId: hello_world
      responses:
        '200':
          description: return hello world message
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/hello_world'
  /users:
    get:
      summary: get users
      operationId: get_users
      responses:
        '200':
          description: return users
          content:
            application/json: 
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'

components:
  schemas:
    hello_world:
      type: object
      properties:
        message:
          type: string
        input:
          type: string
    user:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      required: [id, name]