org: web3ten0
app: lambda-python-test-pj
service: lambda-python-test-pj
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  users:
    handler: user.users
    events:
      - httpApi:
          path: /users
          method: get
